language: node_js
node_js: "10.13.0"


matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
  - name: "OSX"
    os: osx
  - name: "Windows"
    os: windows


install:
  - cd test
  - npm i
