language: node_js
node_js: "10.13.0"


matrix:
  include:
  - name: "Linux Test"
    os: linux
    dist: xenial
    sudo: false
  - name: "OSX Test"
    os: osx
  # TRAVIS BUG: SETTINGS VAR
  # - name: "Windows Test"
  #   os: windows
  - name: "Linux Build"
    os: linux
    env:
      - NEEDS_UPLOAD=true
    if: commit_message =~ /^:hammer:/
    language: cpp
    cache:
      directories:
       - /home/travis/qt-linux
    install:
      - if [[ ! -d /home/travis/qt-linux/Qt ]]; then
          chmod +x ./install-qt.sh;
          chmod +x ./extract-qt-installer.sh;
          export QT_CI_PACKAGES=qt.qt5.5111.gcc_64;
          ./install-qt.sh 5.11.1 /home/travis/qt-linux;
        fi;
      - ls /home/travis/qt-linux/Qt
      - export PATH=/home/travis/qt-linux/Qt/5.11.1/gcc_64/bin:$PATH
    script:
      - qmake -spec linux-g++-64 "INCLUDEPATH+=/home/travis/qt-linux/Qt/5.11.1/gcc_64/include" qt/_qmlui.pro
      - make
  - name: "OSX Build"
    os: osx
    env:
      - NEEDS_UPLOAD=true
    if: commit_message =~ /^:hammer:/
    language: cpp
    compiler: clang++
    cache:
      directories:
       - /Users/travis/qt-osx
    install:
      - if [[ ! -d /Users/travis/qt-osx/Qt ]]; then
          chmod +x ./install-qt.sh;
          chmod +x ./extract-qt-installer.sh;
          export QT_CI_PACKAGES=qt.qt5.5111.clang_64;
          ./install-qt.sh 5.11.1 /Users/travis/qt-osx;
        fi;
      - export PATH=/Users/travis/qt-osx/Qt/5.11.1/clang_64/bin:$PATH
    script:
      - qmake -spec macx-clang "QMAKE_CXXFLAGS+=-ObjC++" "QMAKE_LFLAGS_SONAME=-Wl,-install_name,@rpath/" "INCLUDEPATH+=/Users/travis/qt-osx/Qt/5.11.1/clang_64/include" qt/_qmlui.pro
      - make
      - install_name_tool -change @rpath/QtCore.framework/Versions/5/QtCore @rpath/QtCore bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtNetwork.framework/Versions/5/QtNetwork @rpath/QtNetwork bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtDBus.framework/Versions/5/QtDBus @rpath/QtDBus bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtGui.framework/Versions/5/QtGui @rpath/QtGui bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtWidgets.framework/Versions/5/QtWidgets @rpath/QtWidgets bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtQml.framework/Versions/5/QtQml @rpath/QtQml bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtQuick.framework/Versions/5/QtQuick @rpath/QtQuick bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtQuickControls2.framework/Versions/5/QtQuickControls2 @rpath/QtQuickControls2 bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtQuickTemplates2.framework/Versions/5/QtQuickTemplates2 @rpath/QtQuickTemplates2 bin-mac64/libqmlui.dylib
      - install_name_tool -change @rpath/QtQuickWidgets.framework/Versions/5/QtQuickWidgets @rpath/QtQuickWidgets bin-mac64/libqmlui.dylib

install:
  - cd test
  - npm i

deploy:
  on:
    all_branches: true
    condition: $NEEDS_UPLOAD = true
  provider: releases
  name: "Binaries"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file:
    - bin-linux64/libqmlui.so
    - bin-mac64/libqmlui.dylib
