language: node_js
node_js: "10.13.0"


matrix:
  include:
  - name: "Linux Test"
    os: linux
    dist: xenial
    sudo: false
  - name: "OSX Test"
    os: osx
  - name: "Windows Test"
    os: windows
  - name: "Linux Build"
    os: osx
    env:
      - NEEDS_UPLOAD=true
    if: commit_message =~ /^:hammer:/
    language: cpp
    compiler: clang++
    cache:
      directories:
       - /Users/travis/qt-linux
    install:
      - if [[ ! -d /Users/travis/qt-linux/Qt ]]; then
          chmod +x ./install-qt.sh;
          chmod +x ./extract-qt-installer.sh;
          export QT_CI_PACKAGES=qt.qt5.5111.gcc_64;
          ./install-qt.sh 5.11.1 /Users/travis/qt-linux;
        fi;
      - export PATH=/Users/travis/qt-linux/Qt/5.11.1/clang_64/bin:$PATH
    script:
      - qmake -spec macx-clang "INCLUDEPATH+=/Users/travis/qt-linux/Qt/5.11.1/clang_64/include" qt/_qmlui.pro
      - make
  - name: "OSX Build"
    os: osx
    env:
      - NEEDS_UPLOAD=true
    if: commit_message =~ /^:hammer:/
    language: cpp
    compiler: clang++
    cache:
      directories:
       - /Users/travis/qt-osx
    install:
      - if [[ ! -d /Users/travis/qt-osx/Qt ]]; then
          chmod +x ./install-qt.sh;
          chmod +x ./extract-qt-installer.sh;
          export QT_CI_PACKAGES=qt.qt5.5111.clang_64;
          ./install-qt.sh 5.11.1 /Users/travis/qt-osx;
        fi;
      - export PATH=/Users/travis/qt-osx/Qt/5.11.1/clang_64/bin:$PATH
    script:
      - qmake -spec macx-clang "QMAKE_CXXFLAGS+=-ObjC++" "INCLUDEPATH+=/Users/travis/qt-osx/Qt/5.11.1/clang_64/include" qt/_qmlui.pro
      - make

install:
  - cd test
  - npm i

deploy:
  on:
    all_branches: true
    condition: $NEEDS_UPLOAD = true
  provider: releases
  name: "Binary for OSX"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file:
    - bin-linux64/libqmlui.so
    - bin-mac64/libqmlui.dylib
