matrix:
  include:
    - name: "Linux Test"
      language: node_js
      node_js: "10.16.1"
      os: linux
      if: NOT commit_message =~ /^:hammer:/
      dist: xenial
      sudo: false
      install:
        - cd test
        - npm ci
    - name: "OSX Test"
      language: node_js
      node_js: "10.16.1"
      os: osx
      if: NOT commit_message =~ /^:hammer:/
      install:
        - cd test
        - npm ci
    - name: "Linux Build"
      os: linux
      dist: xenial
      env:
        - NEEDS_UPLOAD=true
        - UPLOAD_FILE=bin-linux/libqmlui.so
        - UPLOAD_NAME=Linux
      if: commit_message =~ /^:hammer:/
      language: cpp
      compiler: gcc
      cache:
        directories:
          - /home/travis/qt-linux
      install:
        - if [[ ! -d /Users/travis/qt-linux/Qt ]]; then
            chmod +x ./install-qt.sh;
            chmod +x ./extract-qt-installer.sh;
            export QT_CI_PACKAGES=qt.qt5.5130.gcc_64;
            ./install-qt.sh 5.13.0 /Users/travis/qt-linux;
          fi;
        - ls
        - export PATH=/home/travis/qt-linux/Qt/5.13.0/gcc_64/bin:$PATH
      script:
        - /home/travis/qt-linux/Qt/5.13.0/gcc_64/bin/qmake -spec linux-g++-64 "INCLUDEPATH+=/home/travis/qt-linux/Qt/5.13.0/gcc_64/include" src/qt/_qmlui.pro
        - make
    - name: "OSX Build"
      os: osx
      env:
        - NEEDS_UPLOAD=true
        - UPLOAD_FILE=bin-osx/libqmlui.dylib
        - UPLOAD_NAME=OSX
      if: commit_message =~ /^:hammer:/
      language: cpp
      compiler: clang++
      cache:
        directories:
          - /Users/travis/qt-osx
      install:
        - if [[ ! -d /Users/travis/qt-osx/Qt ]]; then
            chmod +x ./install-qt.sh;
            chmod +x ./extract-qt-installer.sh;
            export QT_CI_PACKAGES=qt.qt5.5130.clang_64;
            ./install-qt.sh 5.13.0 /Users/travis/qt-osx;
          fi;
        - export PATH=/Users/travis/qt-osx/Qt/5.13.0/clang_64/bin:$PATH
      script:
        - /Users/travis/qt-osx/Qt/5.13.0/clang_64/bin/qmake -spec macx-clang "QMAKE_CXXFLAGS+=-ObjC++" "QMAKE_LFLAGS_SONAME=-Wl,-install_name,@rpath/" "INCLUDEPATH+=/Users/travis/qt-osx/Qt/5.13.0/clang_64/include" src/qt/_qmlui.pro
        - make


deploy:
  on:
    all_branches: true
    condition: $NEEDS_UPLOAD = true
  provider: releases
  name: "$UPLOAD_NAME Binaries"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file:
    - $UPLOAD_FILE
