version: 2.1

workflows:
  pack-binaries:
    jobs:
      - pack-binaries
      - upload-binaries:
          context:
            - github
          requires:
            - pack-binaries

jobs:

  pack-binaries:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - run: python -m pip install setuptools aqtinstall
      - run: |
          cd ~
          python -m aqt install-qt --outputdir ~/Qt linux_arm64 desktop 6.8.0 linux_gcc_arm64
      - checkout
      - run: |
          mkdir -p ~/artifacts
          node -p "require('./package').version" > ~/artifacts/pkg-version
      - run: ~/Qt/6.8.0/gcc_arm64/bin/qmake -spec linux-aarch64-gnu-g++ src/qt/_qmlui.pro
      - run: |
          cd ~
          glibc_install="~/glibc/build/install"
          git clone https://sourceware.org/git/glibc.git
          cd glibc
          git checkout release/2.40/master
          mkdir build
          cd build
          ../configure --prefix "$glibc_install"
          make -j `nproc`
          make install -j `nproc`
          ls $glibc_install
      - run: LD_LIBRARY_PATH=$glibc_install make
      - run: |
          mkdir -p ~/bin_tmp
          cp src/libqmlui.so ~/bin_tmp
          cd ~/bin_tmp && tar -czf ../aarch64.gz *
          mkdir -p ~/artifacts && mv ~/aarch64.gz ~/artifacts
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - aarch64.gz
            - pkg-version

  upload-binaries:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run: go get github.com/tcnksm/ghr
      - run: |
          PKG_VERSION=`cat /tmp/artifacts/pkg-version`
          ghr -u "node-3d" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -n "Release ${PKG_VERSION}" -replace ${PKG_VERSION} /tmp/artifacts/aarch64.gz
