version: 2.1

workflows:
  pack-binaries:
    jobs:
      - pack-binaries
      - upload-binaries:
          context:
            - github
          requires:
            - pack-binaries

jobs:

  pack-binaries:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - restore_cache:
          name: Restore Qt Cache
          key: Qt-6.8.0-v3
      - run: |
          if [ -d "~/Qt" ]; then
            echo "Qt 6.8.0 already installed."
          else
            echo "Downloading Qt 6.8.0."
            python -m pip install setuptools aqtinstall
            cd ~
            python -m aqt install-qt --outputdir ~/Qt linux_arm64 desktop 6.8.0 linux_gcc_arm64
          fi
      - save_cache:
          name: Save Qt Cache
          key: Qt-6.8.0-v3
          paths:
            - ../Qt

      - run: ls
      - checkout
      - run: |
          mkdir -p ~/artifacts
          node -p "require('./package').version" > ~/artifacts/pkg-version
      - run: ~/Qt/6.8.0/gcc_arm64/bin/qmake -spec linux-aarch64-gnu-g++ src/qt/_qmlui.pro

      - restore_cache:
          name: Restore GLIBC Cache
          key: glibc-2.40-v3
      - run: |
          if [ -d "~/glibc" ]; then
            echo "GLIBC 2.40 already cached."
          else
            echo "Building GLIBC 2.40 from source."
            sudo apt-get -y install bison
            cd ~
            git clone --branch release/2.40/master --depth 1 https://sourceware.org/git/glibc.git
            cd glibc
            mkdir build
            cd build
            ../configure --prefix "/home/circleci/glibc/build/install"
            make -j `nproc`
          fi
      - save_cache:
          name: Save GLIBC Cache
          key: glibc-2.40-v3
          paths:
            - ../glibc

      - run: |
          cd ~/glibc/build
          sudo make install -j `nproc`

      - run: make # _qmlui.pro

      - run: |
          mkdir -p ~/bin_tmp
          cp src/libqmlui.so ~/bin_tmp
          cd ~/bin_tmp && tar -czf ../aarch64.gz *
          mkdir -p ~/artifacts && mv ~/aarch64.gz ~/artifacts
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - aarch64.gz
            - pkg-version

  upload-binaries:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run: go get github.com/tcnksm/ghr
      - run: |
          PKG_VERSION=`cat /tmp/artifacts/pkg-version`
          ghr -u "node-3d" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -n "Release ${PKG_VERSION}" -replace ${PKG_VERSION} /tmp/artifacts/aarch64.gz
