name: Build Binaries
defaults:
  run:
    shell: bash

on:
  workflow_dispatch

jobs:
  create_release:
    name: Create Release
    if: contains('["raub"]', github.actor)
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - name: Get Package Version
        id: package-version
        run: node -p "'version='+require('./package').version" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          body: Binaries at ${{ github.sha }}

  build:
    name: Build
    strategy:
        matrix:
          os: [ubuntu-20.04, windows-2022, macos-11]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.13.0'
          cache: 'true'
          cache-key-prefix: 'install-qt-action-${{ matrix.os }}'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Install MSVC
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Current Binary Windows
        if: matrix.os == 'windows-2022'
        run: |
          qmake src/qt/_qmlui.pro
          make
          mkdir bin-windows
          cp src/qmlui.dll bin-windows

      - name: Build Current Binary Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          qmake -spec linux-g++-64 src/qt/_qmlui.pro
          make
          mkdir bin-linux
          cp src/libqmlui.so bin-linux

      - name: Build Current Binary Osx
        if: matrix.os == 'macos-11'
        run: |
          qmake -spec macx-clang "QMAKE_CXXFLAGS+=-ObjC++" "QMAKE_LFLAGS_SONAME=-Wl,-install_name,@rpath/" src/qt/_qmlui.pro
          make
          mkdir bin-osx
          cp src/libqmlui.dylib bin-osx

      - name: Get Package Version
        id: package-version
        run: node -p "'version='+require('./package').version" >> $GITHUB_OUTPUT

      - name: Pack Files
        id: pack-files
        run: node -e "require('addon-tools-raub').actionPack()" >> $GITHUB_OUTPUT

      - name: Store Binaries
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          files: ${{ steps.pack-files.outputs.pack }}
