name: Build
defaults:
  run:
    shell: bash

on:
  workflow_dispatch

jobs:
  create_release:
    name: Create Release
    if: contains('["raub"]', github.actor)
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: 'npm'

      - name: Get Package Version
        id: package-version
        run: node -p "'version='+require('./package').version" >> $GITHUB_OUTPUT

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}

  build:
    name: Build
    strategy:
        matrix:
          os: [ubuntu-22.04, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          cache: 'true'
          cache-key-prefix: 'install-qt-${{ matrix.os }}'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Install MSVC
        if: matrix.os == 'windows-2022'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build - Windows
        if: matrix.os == 'windows-2022'
        run: |
          echo "OS_NAME=windows" >> $GITHUB_ENV
          qmake -spec win32-msvc src/qt/_qmlui.pro
          mv /usr/bin/link.exe /usr/bin/1link.exe
          nmake
          mv /usr/bin/1link.exe /usr/bin/link.exe
          rm -rf bin-windows
          mkdir bin-windows
          cp src/qmlui.dll bin-windows
          cp src/qmlui.lib bin-windows

      - name: Build - Linux
        if: matrix.os == 'ubuntu-22.04'
        run: |
          echo "OS_NAME=linux" >> $GITHUB_ENV
          qmake -spec linux-g++-64 src/qt/_qmlui.pro
          make
          rm -rf bin-linux
          mkdir bin-linux
          cp src/libqmlui.so bin-linux

      - name: Build - MacOS ARM
        if: matrix.os == 'macos-14'
        run: |
          echo "OS_NAME=darwin-arm64" >> $GITHUB_ENV
          qmake -spec macx-clang "QMAKE_CXXFLAGS+=-ObjC++" "QMAKE_LFLAGS_SONAME=-Wl,-install_name,@rpath/" "INCLUDEPATH+=${{ github.workspace }}/../Qt/6.8.0/macos/include" src/qt/_qmlui.pro
          make
          rm -rf bin-darwin-arm64
          mkdir bin-darwin-arm64
          cp src/libqmlui.dylib bin-darwin-arm64

      - name: Get Package Version
        id: package-version
        run: node -p "'version='+require('./package').version" >> $GITHUB_OUTPUT

      - name: Pack Files
        run: |
          cd 'bin-${{ env.OS_NAME }}'
          tar -czf ../${{ env.OS_NAME }}.gz *

      - name: Store Binaries
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.version }}
          name: Release ${{ steps.package-version.outputs.version }}
          files: ${{ env.OS_NAME }}.gz
